name: E2E Test

description: Run an E2E test suite

env:
  test_results_path: coverage-devhub-tests-results.html

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Name for the uploaded artifact'
        required: false
        default: 'test-results'
      pytest_marker:
        description: 'Pytest marker expression (-m)'
        required: false
        default: ''
      pytest_parallel:
        description: 'The number of parallel tests to run'
        required: false
        default: '1'
      pytest_path:
        description: 'The path to the test to run'
        required: true
        default: ''
      pytest_report:
        description: 'Name for the HTML report file'
        required: false
        default: 'test-results.html'
      pytest_reruns:
        description: 'The number of times to rerun the tests'
        required: false
        default: '2'
      pytest_variables:
        description: 'The path to the variables file'
        type: choice
        required: true
        options:
          - dev.json
          - stage.json
          - prod.json
      python_version:
        description: 'The Python version to use'
        required: false
        default: '3.11'
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      pytest_marker:
        required: false
        type: string
        default: ''
      pytest_parallel:
        required: true
        type: string
      pytest_path:
        required: true
        type: string
      pytest_report:
        required: true
        type: string
      pytest_reruns:
        required: true
        type: string
      pytest_variables:
        required: true
        type: string
      python_version:
        required: false
        type: string
        default: '3.11'
jobs:
  test:
    name: ${{ inputs.pytest_report }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'pip'
        cache-dependency-path: ./requirements.txt

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install requirements
      run: python -m pip install --no-deps -r ./requirements.txt

    - name: Debug pip cache
      run: |
        echo "Pip cache dir: $(python -m pip cache dir)"
        ls -l "$(python -m pip cache dir)"

    - name: Install geckodriver and Firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: latest

    - name: Verify Firefox Installation
      shell: bash
      run: |
        echo Installed Firefox version:
        which firefox
        firefox --version

    - name: Install Setup Tools
      run: pip install setuptools

    - name: Run tests
      timeout-minutes: 30
      shell: bash
      env:
        MOZ_HEADLESS: 1
      run: |
        IFS=',' read -ra items <<< "$input"
        variables=""
        for item in "${items[@]}"; do
          variables+="--variables $item "
        done


        python -m pytest ${{ inputs.pytest_path }} \
          -n ${{ inputs.pytest_parallel }} \
          -m ${{ inputs.pytest_marker }} \
          --reruns ${{ inputs.pytest_reruns }} \
          --driver Firefox \
          $variables \
          --html=${{ inputs.pytest_report }} \
          --self-contained-html

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.pytest_report }}

